# Default values for slack.
replicaCount: 1

image:
  repository: networkperspective.azurecr.io/connectors/slack
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

appSettings:
  connectionString: ""
  logLevel: info
  secretRotationEnabled: true

secrets:
  slackSecrets: "np-sync-slack-secrets"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: 
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: slack.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 1
    memory: 4G
  requests:
    cpu: 400m
    memory: 2G

nodeSelector: {}

tolerations: []

affinity: {}

logVolume:
  enabled: false
  existingDataClaim: ""
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 1Gi
  annotations: {}