---
# Source: np-sync/charts/gsuite/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: np-sync-gsuite
  labels:
    helm.sh/chart: gsuite-0.1.0
    app.kubernetes.io/name: gsuite
    app.kubernetes.io/instance: np-sync
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: np-sync/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: np-sync
  labels:
    helm.sh/chart: np-sync-0.1.0
    app.kubernetes.io/name: np-sync
    app.kubernetes.io/instance: np-sync
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: np-sync/charts/mssql/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: np-sync-mssql-secret
  labels:
    app: np-sync-mssql
    chart: mssql-1.2.3
    release: np-sync
    heritage: Helm
type: Opaque
data:
  
  sapassword: "WTRrN3d1TnprMW5QS3VVT1lnaFk="
---
# Source: np-sync/charts/mssql/templates/pvc-data.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: np-sync-mssql-data
  labels:
    app: np-sync-mssql
    chart: "mssql-1.2.3"
    release: "np-sync"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: np-sync/charts/gsuite/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: np-sync-gsuite
  labels:
    helm.sh/chart: gsuite-0.1.0
    app.kubernetes.io/name: gsuite
    app.kubernetes.io/instance: np-sync
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gsuite
    app.kubernetes.io/instance: np-sync
---
# Source: np-sync/charts/mssql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: np-sync-mssql
  labels:
    app: np-sync-mssql
    chart: mssql-1.2.3
    release: np-sync
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - name: mssql
    port: 1433
    targetPort: mssql
    protocol: TCP
  selector:
    app: np-sync-mssql
    release: np-sync
---
# Source: np-sync/charts/gsuite/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-sync-gsuite
  labels:
    helm.sh/chart: gsuite-0.1.0
    app.kubernetes.io/name: gsuite
    app.kubernetes.io/instance: np-sync
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gsuite
      app.kubernetes.io/instance: np-sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gsuite
        app.kubernetes.io/instance: np-sync
    spec:
      serviceAccountName: np-sync-gsuite
      securityContext:
        {}
      containers:
        - name: gsuite
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: np-sync/charts/mssql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-sync-mssql
  labels:
    app: np-sync-mssql
    chart: mssql-1.2.3
    release: np-sync
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: np-sync-mssql
      release: np-sync
  template:
    metadata:
      labels:
        app: np-sync-mssql
        release: np-sync
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql
          image: "mcr.microsoft.com/mssql/server:2022-latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
            - name: SA_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: np-sync-mssql-secret
                 key: sapassword
            - name: MSSQL_DATA_DIR
              value: /var/opt/mssql
            - name: MSSQL_TCP_PORT
              value: "1433"
            - name: MSSQL_COLLATION
              value: "SQL_Latin1_General_CP1_CI_AS"
            - name: MSSQL_LCID
              value: "1033"
            - name: MSSQL_ENABLE_HADR
              value: "0"
            
            - name: MSSQL_MEMORY_LIMIT_MB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            
          ports:
            - name: mssql
              containerPort: 1433
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql
          livenessProbe:
             tcpSocket:
               port: mssql
             initialDelaySeconds: 15
             periodSeconds: 20
          readinessProbe:
             tcpSocket:
               port: mssql
             initialDelaySeconds: 5
             periodSeconds: 10
          resources:
            limits:
              memory: 2Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: np-sync-mssql-data
---
# Source: np-sync/charts/gsuite/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "np-sync-gsuite-test-connection"
  labels:
    helm.sh/chart: gsuite-0.1.0
    app.kubernetes.io/name: gsuite
    app.kubernetes.io/instance: np-sync
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['np-sync-gsuite:80']
  restartPolicy: Never
---
# Source: np-sync/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "np-sync-test-connection"
  labels:
    helm.sh/chart: np-sync-0.1.0
    app.kubernetes.io/name: np-sync
    app.kubernetes.io/instance: np-sync
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['np-sync:80']
  restartPolicy: Never
