# gcp unseal config
vault:
  server:
    standalone:
      config: |
        ui = true
        
        storage "file" {
          path = "/vault/data"
        }
        listener "tcp" {
          address       = "0.0.0.0:8200"
          tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-tls/tls.key"
        }
        seal "gcpckms" {
          credentials = "/vault/userconfig/kms-creds/np-sync-vault-sa.json"
          project     = "network-perspective-sync"
          region      = "global"
          key_ring    = "vault-keyring"
          crypto_key  = "unseal-key"
        }
    volumes:
    - name: vault-tls
      secret:
        defaultMode: 0420
        secretName: np-sync-tls-prod
    - name: gcp-unseal
      secret:
        defaultMode: 0420
        secretName: np-sync-vault-sa
    volumeMounts:
    - mountPath: "/vault/userconfig/vault-tls"
      name: vault-tls
      readOnly: true
    - mountPath: "/vault/userconfig/kms-creds"
      name: gcp-unseal
      readOnly: true
    extraEnvironmentVars:      
      