apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: np-sync-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        ebs: true