@orchestrator_host = https://localhost:7191
@worker_id = f0d39021-a738-4535-84d5-d5399564128f
@network_id = bd1bc916-db78-4e1e-b93b-c6feb8cf729e
@connector_id = 04C753D8-FF9A-479C-B857-5D28C1EAF6C1
@api_key = api-key
##
### WORKERS GET ALL
GET {{orchestrator_host}}/api/workers
Authorization: Bearer {{api_key}}
Accept: application/json

### WORKERS CREATE
POST {{orchestrator_host}}/api/workers
Authorization: Bearer {{api_key}}
Content-Type: application/json
Accept: application/json

{
    "Name": "client_1",
    "Secret": "pass1"
}

### WORKERS AUTHORIZE
POST {{orchestrator_host}}/api/workers/{{worker_id}}/auth
Authorization: Bearer {{api_key}}
Accept: application/json

### WORKERS DELETE

DELETE {{orchestrator_host}}/api/workers/{{worker_id}}
Authorization: Bearer {{api_key}}
Content-Type: application/json

### CONNECTORS GET ALL
GET {{orchestrator_host}}/api/connectors?workerId={{worker_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{api_key}}

### CONNECTORS CREATE
POST {{orchestrator_host}}/api/connectors
Authorization: Bearer {{api_key}}
Content-Type: application/json
Accept: application/json

{
    "Id": "{{connector_id}}",
    "NetworkId": "{{network_id}}",
    "WorkerId": "{{worker_id}}",
    "Type": "Slack",
    "AccessToken": "access_token",
    "Properties": [
        { "Key": "key1", "Value": "value1" },
        { "Key": "key2", "Value": "value2" }
    ]
}

### SCHEDULER CREATE
POST {{orchestrator_host}}/api/connectors/{{connector_id}}/schedules
Authorization: Bearer {{api_key}}
Content-Type: application/json
Accept: application/json

{
    "OverrideSyncPeriodStart": "2024-01-01T00:00:00Z"
}

### SCHEDULER REMOVE
DELETE {{orchestrator_host}}/api/connectors/{{connector_id}}/schedules
Authorization: Bearer {{api_key}}
Content-Type: application/json
Accept: application/json

{

}

### START AUTH SLACK
POST {{orchestrator_host}}/api/connectors/slack-auth?connectorId={{connector_id}}
Authorization: Bearer {{api_key}}
Accept: application/json
