acceptEula:
  value: "n"
edition:
  value: Express
collation: SQL_Latin1_General_CP1_CI_AS
dataDir: /var/opt/mssql
lcid: 1033
hadr: 0
replicaCount: 1
# Override sapassword in templates/secret.yaml
# sapassword: "MyStrongPassword1234"
image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2022-latest
  pullPolicy: IfNotPresent
  
service:
  headless: false
  type: ClusterIP
  port: 1433
  annotations: {}
  labels: {}
deployment:
  annotations: {}
  labels: {}
pod:
  annotations: {}
  labels: {}
persistence:
  enabled: true
  # existingDataClaim:
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 1Gi
  annotations: {
    helm.sh/resource-policy: keep,
    tilt.dev/down-policy: keep
  }
livenessprobe:
  initialDelaySeconds: 15
  periodSeconds: 20
readinessprobe:
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi