// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkPerspective.Sync.Infrastructure.Persistence;

#nullable disable

namespace NetworkPerspective.Sync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConnectorDbContext))]
    partial class ConnectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Networks", (string)null);
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkPropertyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("NetworkProperties", (string)null);
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.StatusLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Level")
                        .HasMaxLength(1024)
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("StatusLogs", (string)null);
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.SyncHistoryEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("InteractionsCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SuccessRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("SyncPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("TasksCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("SyncHistory", (string)null);
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkPropertyEntity", b =>
                {
                    b.HasOne("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkEntity", "Network")
                        .WithMany("Properties")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.StatusLogEntity", b =>
                {
                    b.HasOne("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkEntity", "Network")
                        .WithMany()
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.SyncHistoryEntryEntity", b =>
                {
                    b.HasOne("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkEntity", "Network")
                        .WithMany("SyncHistory")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("NetworkPerspective.Sync.Infrastructure.Persistence.Entities.NetworkEntity", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("SyncHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
