appSettings:
  networkPerspectiveApi: https://staging.networkperspective.io/
  awsSecretsManagerRegion: eu-central-1
  awsSecretsManagerPrefix: networkperspective/worker

extraEnvironmentVars:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: np-worker-aws-secret
        key: aws_access_key_id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: np-worker-aws-secret
        key: aws_secret_access_key
  - name: Logging__LogLevel__Default
    value: Debug