# Default values for gsuite.
replicaCount: 1

image:
  repository: networkperspective.azurecr.io/connectors/gsuite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

appSettings:
  connectionString: ""
  logLevel: info

secrets:
  googleKeys: "np-sync-gsuite-secrets"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

domainValidation:
  enabled: true
  hostedZoneName: gsuite-01.test.networkperspective.io

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: gsuite.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 500m
    memory: 4G
  requests:
    cpu: 500m
    memory: 0.5G

nodeSelector: {}

tolerations: []

affinity: {}

logVolume:
  enabled: false
  existingDataClaim: ""
  storageClass: ""
  dataAccessMode: ReadWriteOnce
  dataSize: 1Gi
  annotations: {}