{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ip-whitelist
spec:
  podSelector: {}  # Apply to all pods in the namespace
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        {{- range .Values.networkPolicy.ipWhitelist }}
        - {{ . }}
        {{- end }}
{{- end }}
