{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: default
spec:
  podSelector: {} # Applies to all Pods in the namespace
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {} # Allows traffic from all Pods in the namespace
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to:
    - podSelector: {} # Allows traffic to all Pods in the namespace
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0 # Allows egress to the Internet
{{- end }}
