{{- if .Values.global.domainValidation.enabled }}
{{- $issuerName := printf "%s-azure-dns-issuer" .Values.global.tlsSecret -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $issuerName }}
spec:
  acme:
    {{- if eq .Values.global.domainValidation.environment "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: {{ $issuerName }}
    email: {{ .Values.global.domainValidation.email }}
    solvers:    
    - dns01:
        azureDNS:
          clientID: {{ .Values.global.domainValidation.clientID}}
          clientSecretSecretRef:
            name: {{ .Values.global.domainValidation.clientSecretRef }}
            key: clientSecret
          subscriptionID: {{ .Values.global.domainValidation.subscriptionID }}
          tenantID: {{ .Values.global.domainValidation.tenantID }}
          resourceGroupName: {{ .Values.global.domainValidation.resourceGroupName }}
          environment: AzurePublicCloud
          hostedZoneName: {{ .Values.global.domainValidation.hostedZoneName }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.tlsSecret }}-certificate
spec:
  secretName: {{ .Values.global.tlsSecret }}
  issuerRef:
    name: {{ $issuerName }}
    kind: Issuer
  commonName: {{ .Values.global.domainValidation.hostedZoneName }}
  dnsNames:
    - {{ .Values.global.domainValidation.hostedZoneName }}
    {{- range .Values.gsuite.ingress.tls }}
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}        
    {{- range .Values.slack.ingress.tls }}
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}        
    {{- range .Values.excel.ingress.tls }}
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}        
{{- end }}